"use client"
import { Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,XAxis,YAxis } from "recharts"
import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card"
import { ChartContainer,ChartTooltip,ChartTooltipContent,type ChartConfig } from "@/components/ui/chart"
import { useSigia } from "@/lib/store"
import { PRIORITIES,priorityLabel } from "@/lib/types"
const createdConfig={creadas:{label:"Creadas",color:"var(--chart-1)"},resueltas:{label:"Resueltas",color:"var(--chart-3)"}} satisfies ChartConfig
const priorityConfig={value:{label:"Incidencias"},critica:{label:"Crítica",color:"var(--priority-critical)"},alta:{label:"Alta",color:"var(--priority-high)"},media:{label:"Media",color:"var(--priority-medium)"},baja:{label:"Baja",color:"var(--priority-low)"}} satisfies ChartConfig
const deptConfig={value:{label:"Incidencias",color:"var(--chart-2)"}} satisfies ChartConfig
export function DashboardCharts(){const{incidents}=useSigia();
 const monthly=new Map<string,{month:string,creadas:number,resueltas:number}>(); incidents.forEach(i=>{const d=new Date(i.createdAt);if(Number.isNaN(d.getTime()))return;const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;const label=d.toLocaleDateString("es-CL",{month:"short",year:"2-digit"});const x=monthly.get(k)||{month:label,creadas:0,resueltas:0};x.creadas++;if(["resuelta","cerrada"].includes(i.status))x.resueltas++;monthly.set(k,x)});const created=[...monthly.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([,v])=>v);
 const priorityData=PRIORITIES.map(p=>({name:priorityLabel(p.value),key:p.value,value:incidents.filter(i=>i.priority===p.value).length,fill:`var(--color-${p.token})`}));
 const deptMap=new Map<string,number>();incidents.forEach(i=>deptMap.set(i.department,(deptMap.get(i.department)||0)+1));const deptData=[...deptMap].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value).slice(0,10);
 return <div className="grid grid-cols-1 gap-4 lg:grid-cols-2"><Card className="lg:col-span-2"><CardHeader><CardTitle>Creadas vs. resueltas</CardTitle><CardDescription>Calculado desde las incidencias almacenadas en SIGIA</CardDescription></CardHeader><CardContent><ChartContainer config={createdConfig} className="h-64 w-full"><AreaChart data={created}><CartesianGrid vertical={false}/><XAxis dataKey="month"/><YAxis/><ChartTooltip content={<ChartTooltipContent/>}/><Area dataKey="creadas" stroke="var(--color-creadas)" fill="var(--color-creadas)" fillOpacity={.15}/><Area dataKey="resueltas" stroke="var(--color-resueltas)" fill="var(--color-resueltas)" fillOpacity={.15}/></AreaChart></ChartContainer></CardContent></Card><Card><CardHeader><CardTitle>Por prioridad</CardTitle><CardDescription>Distribución real actual</CardDescription></CardHeader><CardContent><ChartContainer config={priorityConfig} className="mx-auto h-64 w-full"><PieChart><ChartTooltip content={<ChartTooltipContent nameKey="name" hideLabel/>}/><Pie data={priorityData} dataKey="value" nameKey="name" innerRadius={55}>{priorityData.map(d=><Cell key={d.key} fill={d.fill}/>)}</Pie></PieChart></ChartContainer></CardContent></Card><Card><CardHeader><CardTitle>Por departamento</CardTitle><CardDescription>Incluye Alma y áreas provenientes del registro real</CardDescription></CardHeader><CardContent><ChartContainer config={deptConfig} className="h-64 w-full"><BarChart data={deptData} layout="vertical"><CartesianGrid horizontal={false}/><XAxis type="number"/><YAxis type="category" dataKey="name" width={130} tick={{fontSize:11}}/><ChartTooltip content={<ChartTooltipContent/>}/><Bar dataKey="value" fill="var(--color-value)" radius={[0,6,6,0]}/></BarChart></ChartContainer></CardContent></Card></div>}
