import type { Incident, User, KbArticle } from "./types"

export const CURRENT_USER = {
  name: "Adriano Lecaros",
  email: "adriano.lecaros@sigia.io",
  role: "administrador" as const,
  initials: "AL",
}

const tech = ["Camila Rojas", "Diego Fuentes", "Valentina Soto", "Matías Herrera", "Adriano Lecaros"]

function mkComments(...items: [string, Incident["comments"][number]["role"], string, string][]): Incident["comments"] {
  return items.map((c, i) => ({
    id: `c${i}`,
    author: c[0],
    role: c[1],
    content: c[2],
    createdAt: c[3],
  }))
}

export const INCIDENTS: Incident[] = [
  {
    id: "INC-0127",
    title: "Error al ingresar al sistema de agenda",
    description:
      "Al intentar iniciar sesión en el sistema de agenda corporativa, aparece el mensaje 'Credenciales inválidas' pese a usar la contraseña correcta. El problema afecta a todo el equipo de recepción desde esta mañana y bloquea la gestión de citas.",
    requester: "María González",
    department: "Operaciones",
    category: "Accesos",
    priority: "critica",
    status: "en_progreso",
    assignee: "Camila Rojas",
    location: "Edificio Central — Piso 2",
    createdAt: "2026-08-14T08:12:00",
    updatedAt: "2026-08-14T09:40:00",
    slaDueAt: "2026-08-14T12:12:00",
    slaBreached: false,
    attachments: [
      { name: "captura-error-login.png", size: "248 KB", type: "image/png" },
      { name: "log-agenda.txt", size: "12 KB", type: "text/plain" },
    ],
    comments: mkComments(
      ["María González", "usuario", "Sigue sin funcionar, necesitamos acceso urgente para atender pacientes.", "2026-08-14T08:30:00"],
      ["Camila Rojas", "tecnico", "Estoy revisando el servicio de autenticación (SSO). Detecté que el token expiró en el proveedor de identidad.", "2026-08-14T09:15:00"],
    ),
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por María González", author: "María González", createdAt: "2026-08-14T08:12:00" },
      { id: "t2", type: "asignada", description: "Asignada a Camila Rojas", author: "Adriano Lecaros", createdAt: "2026-08-14T08:20:00" },
      { id: "t3", type: "estado", description: "Estado cambiado a En progreso", author: "Camila Rojas", createdAt: "2026-08-14T09:10:00" },
    ],
  },
  {
    id: "INC-0126",
    title: "Impresora del piso 3 no responde",
    description: "La impresora multifuncional HP del piso 3 no imprime ni escanea. El panel muestra error 49.4C02.",
    requester: "Jorge Núñez",
    department: "Finanzas",
    category: "Impresoras",
    priority: "media",
    status: "asignada",
    assignee: "Diego Fuentes",
    location: "Edificio Central — Piso 3",
    createdAt: "2026-08-14T07:45:00",
    updatedAt: "2026-08-14T08:05:00",
    slaDueAt: "2026-08-15T07:45:00",
    slaBreached: false,
    attachments: [],
    comments: mkComments(
      ["Diego Fuentes", "tecnico", "Voy a reiniciar el firmware de la impresora esta tarde.", "2026-08-14T08:05:00"],
    ),
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Jorge Núñez", author: "Jorge Núñez", createdAt: "2026-08-14T07:45:00" },
      { id: "t2", type: "asignada", description: "Asignada a Diego Fuentes", author: "Adriano Lecaros", createdAt: "2026-08-14T08:00:00" },
    ],
  },
  {
    id: "INC-0125",
    title: "VPN se desconecta constantemente",
    description: "La VPN corporativa se desconecta cada 5-10 minutos afectando el trabajo remoto del equipo de ventas.",
    requester: "Paula Vega",
    department: "Ventas",
    category: "Red",
    priority: "alta",
    status: "en_progreso",
    assignee: "Matías Herrera",
    location: "Remoto",
    createdAt: "2026-08-13T16:20:00",
    updatedAt: "2026-08-14T09:00:00",
    slaDueAt: "2026-08-14T10:20:00",
    slaBreached: false,
    attachments: [{ name: "diagnostico-red.pdf", size: "1.2 MB", type: "application/pdf" }],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Paula Vega", author: "Paula Vega", createdAt: "2026-08-13T16:20:00" },
      { id: "t2", type: "asignada", description: "Asignada a Matías Herrera", author: "Adriano Lecaros", createdAt: "2026-08-13T16:45:00" },
    ],
  },
  {
    id: "INC-0124",
    title: "Solicitud de nueva licencia de Office 365",
    description: "Nuevo colaborador requiere licencia de Office 365 y acceso al correo corporativo.",
    requester: "Andrés Pino",
    department: "Recursos Humanos",
    category: "Software",
    priority: "baja",
    status: "nueva",
    assignee: null,
    location: "Edificio Norte — Piso 1",
    createdAt: "2026-08-13T14:10:00",
    updatedAt: "2026-08-13T14:10:00",
    slaDueAt: "2026-08-16T14:10:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Andrés Pino", author: "Andrés Pino", createdAt: "2026-08-13T14:10:00" },
    ],
  },
  {
    id: "INC-0123",
    title: "Servidor de correo con latencia elevada",
    description: "El servidor de correo presenta demoras de hasta 15 minutos en la entrega de mensajes internos.",
    requester: "Lucía Ramírez",
    department: "TI",
    category: "Sistemas",
    priority: "critica",
    status: "en_espera",
    assignee: "Adriano Lecaros",
    location: "Data Center",
    createdAt: "2026-08-13T11:00:00",
    updatedAt: "2026-08-14T08:30:00",
    slaDueAt: "2026-08-13T15:00:00",
    slaBreached: true,
    attachments: [{ name: "metricas-servidor.xlsx", size: "540 KB", type: "spreadsheet" }],
    comments: mkComments(
      ["Adriano Lecaros", "administrador", "En espera de ventana de mantenimiento aprobada por Gerencia.", "2026-08-14T08:30:00"],
    ),
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Lucía Ramírez", author: "Lucía Ramírez", createdAt: "2026-08-13T11:00:00" },
      { id: "t2", type: "sla", description: "SLA vencido", author: "Sistema", createdAt: "2026-08-13T15:00:00" },
      { id: "t3", type: "estado", description: "Estado cambiado a En espera", author: "Adriano Lecaros", createdAt: "2026-08-14T08:30:00" },
    ],
  },
  {
    id: "INC-0122",
    title: "No carga el módulo de reportes del ERP",
    description: "El módulo de reportes del ERP muestra pantalla en blanco al generar informes de ventas mensuales.",
    requester: "Felipe Castro",
    department: "Ventas",
    category: "Sistemas",
    priority: "alta",
    status: "asignada",
    assignee: "Valentina Soto",
    location: "Edificio Central — Piso 4",
    createdAt: "2026-08-13T09:30:00",
    updatedAt: "2026-08-13T10:00:00",
    slaDueAt: "2026-08-14T09:30:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Felipe Castro", author: "Felipe Castro", createdAt: "2026-08-13T09:30:00" },
      { id: "t2", type: "asignada", description: "Asignada a Valentina Soto", author: "Adriano Lecaros", createdAt: "2026-08-13T09:50:00" },
    ],
  },
  {
    id: "INC-0121",
    title: "Notebook con pantalla azul recurrente",
    description: "Notebook Dell presenta pantalla azul (BSOD) varias veces al día, error MEMORY_MANAGEMENT.",
    requester: "Carolina Díaz",
    department: "Marketing",
    category: "Hardware",
    priority: "media",
    status: "resuelta",
    assignee: "Diego Fuentes",
    location: "Edificio Norte — Piso 2",
    createdAt: "2026-08-12T13:15:00",
    updatedAt: "2026-08-13T17:00:00",
    slaDueAt: "2026-08-13T13:15:00",
    slaBreached: false,
    attachments: [],
    comments: mkComments(
      ["Diego Fuentes", "tecnico", "Se reemplazó el módulo de RAM defectuoso. Equipo estable tras 24h de pruebas.", "2026-08-13T16:50:00"],
    ),
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Carolina Díaz", author: "Carolina Díaz", createdAt: "2026-08-12T13:15:00" },
      { id: "t2", type: "resuelta", description: "Incidencia resuelta", author: "Diego Fuentes", createdAt: "2026-08-13T17:00:00" },
    ],
  },
  {
    id: "INC-0120",
    title: "Acceso denegado a carpeta compartida de Finanzas",
    description: "Varios usuarios de Finanzas no pueden acceder a la carpeta compartida \\\\srv-fin\\cierre-mensual.",
    requester: "Roberto Salas",
    department: "Finanzas",
    category: "Accesos",
    priority: "alta",
    status: "cerrada",
    assignee: "Camila Rojas",
    location: "Edificio Central — Piso 3",
    createdAt: "2026-08-11T10:00:00",
    updatedAt: "2026-08-12T09:00:00",
    slaDueAt: "2026-08-12T10:00:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Roberto Salas", author: "Roberto Salas", createdAt: "2026-08-11T10:00:00" },
      { id: "t2", type: "resuelta", description: "Permisos restaurados en Active Directory", author: "Camila Rojas", createdAt: "2026-08-11T18:00:00" },
      { id: "t3", type: "estado", description: "Incidencia cerrada", author: "Adriano Lecaros", createdAt: "2026-08-12T09:00:00" },
    ],
  },
  {
    id: "INC-0119",
    title: "Integración con pasarela de pagos falla",
    description: "La integración con la pasarela de pagos devuelve error 500 en el 20% de las transacciones.",
    requester: "Sofía Miranda",
    department: "Ventas",
    category: "Integraciones",
    priority: "critica",
    status: "en_progreso",
    assignee: "Valentina Soto",
    location: "Remoto",
    createdAt: "2026-08-12T15:40:00",
    updatedAt: "2026-08-14T08:00:00",
    slaDueAt: "2026-08-12T19:40:00",
    slaBreached: true,
    attachments: [{ name: "logs-pasarela.txt", size: "88 KB", type: "text/plain" }],
    comments: mkComments(
      ["Valentina Soto", "tecnico", "El certificado TLS del webhook expiró. Renovando y coordinando con el proveedor.", "2026-08-14T08:00:00"],
    ),
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Sofía Miranda", author: "Sofía Miranda", createdAt: "2026-08-12T15:40:00" },
      { id: "t2", type: "sla", description: "SLA vencido", author: "Sistema", createdAt: "2026-08-12T19:40:00" },
    ],
  },
  {
    id: "INC-0118",
    title: "Teclado inalámbrico sin respuesta",
    description: "Teclado inalámbrico logitech no responde tras cambio de pilas. Se probó nuevo receptor USB.",
    requester: "Ignacio Bravo",
    department: "Legal",
    category: "Hardware",
    priority: "baja",
    status: "resuelta",
    assignee: "Matías Herrera",
    location: "Edificio Central — Piso 5",
    createdAt: "2026-08-11T09:00:00",
    updatedAt: "2026-08-11T11:30:00",
    slaDueAt: "2026-08-14T09:00:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Ignacio Bravo", author: "Ignacio Bravo", createdAt: "2026-08-11T09:00:00" },
      { id: "t2", type: "resuelta", description: "Equipo reemplazado", author: "Matías Herrera", createdAt: "2026-08-11T11:30:00" },
    ],
  },
  {
    id: "INC-0117",
    title: "Wi-Fi lento en sala de reuniones",
    description: "La señal Wi-Fi en la sala de reuniones principal es intermitente durante videollamadas.",
    requester: "Daniela Fuentes",
    department: "Gerencia",
    category: "Red",
    priority: "media",
    status: "asignada",
    assignee: "Matías Herrera",
    location: "Edificio Central — Piso 6",
    createdAt: "2026-08-13T12:00:00",
    updatedAt: "2026-08-13T12:20:00",
    slaDueAt: "2026-08-14T12:00:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Daniela Fuentes", author: "Daniela Fuentes", createdAt: "2026-08-13T12:00:00" },
    ],
  },
  {
    id: "INC-0116",
    title: "Error de sincronización con CRM",
    description: "Los contactos nuevos no se sincronizan entre el CRM y la plataforma de email marketing.",
    requester: "Tomás Araya",
    department: "Marketing",
    category: "Integraciones",
    priority: "alta",
    status: "nueva",
    assignee: null,
    location: "Remoto",
    createdAt: "2026-08-14T09:00:00",
    updatedAt: "2026-08-14T09:00:00",
    slaDueAt: "2026-08-14T13:00:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Tomás Araya", author: "Tomás Araya", createdAt: "2026-08-14T09:00:00" },
    ],
  },
  {
    id: "INC-0115",
    title: "Solicitud de restablecer contraseña de dominio",
    description: "Usuario olvidó su contraseña de dominio y quedó bloqueado tras varios intentos.",
    requester: "Javiera Muñoz",
    department: "Recursos Humanos",
    category: "Accesos",
    priority: "media",
    status: "cerrada",
    assignee: "Camila Rojas",
    location: "Edificio Norte — Piso 1",
    createdAt: "2026-08-10T08:30:00",
    updatedAt: "2026-08-10T09:00:00",
    slaDueAt: "2026-08-10T12:30:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Javiera Muñoz", author: "Javiera Muñoz", createdAt: "2026-08-10T08:30:00" },
      { id: "t2", type: "resuelta", description: "Contraseña restablecida", author: "Camila Rojas", createdAt: "2026-08-10T08:50:00" },
    ],
  },
  {
    id: "INC-0114",
    title: "Monitor externo no detectado",
    description: "El monitor externo no es detectado al conectar vía HDMI en estación de trabajo.",
    requester: "Cristóbal León",
    department: "Operaciones",
    category: "Hardware",
    priority: "baja",
    status: "en_progreso",
    assignee: "Diego Fuentes",
    location: "Edificio Central — Piso 2",
    createdAt: "2026-08-13T15:00:00",
    updatedAt: "2026-08-14T08:15:00",
    slaDueAt: "2026-08-16T15:00:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Cristóbal León", author: "Cristóbal León", createdAt: "2026-08-13T15:00:00" },
    ],
  },
  {
    id: "INC-0113",
    title: "Aplicación de escritorio se cierra inesperadamente",
    description: "La aplicación contable se cierra al exportar libros mayores en formato PDF.",
    requester: "Fernanda Rojas",
    department: "Finanzas",
    category: "Software",
    priority: "alta",
    status: "en_progreso",
    assignee: "Valentina Soto",
    location: "Edificio Central — Piso 3",
    createdAt: "2026-08-13T10:30:00",
    updatedAt: "2026-08-14T07:50:00",
    slaDueAt: "2026-08-14T06:30:00",
    slaBreached: true,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Fernanda Rojas", author: "Fernanda Rojas", createdAt: "2026-08-13T10:30:00" },
      { id: "t2", type: "sla", description: "SLA vencido", author: "Sistema", createdAt: "2026-08-14T06:30:00" },
    ],
  },
  {
    id: "INC-0112",
    title: "Configuración de nuevo correo corporativo",
    description: "Solicitud de creación de casilla de correo para nueva sucursal en región.",
    requester: "Gonzalo Tapia",
    department: "TI",
    category: "Sistemas",
    priority: "baja",
    status: "resuelta",
    assignee: "Adriano Lecaros",
    location: "Sucursal Sur",
    createdAt: "2026-08-09T11:00:00",
    updatedAt: "2026-08-09T14:00:00",
    slaDueAt: "2026-08-12T11:00:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Gonzalo Tapia", author: "Gonzalo Tapia", createdAt: "2026-08-09T11:00:00" },
      { id: "t2", type: "resuelta", description: "Casilla creada y configurada", author: "Adriano Lecaros", createdAt: "2026-08-09T14:00:00" },
    ],
  },
  {
    id: "INC-0111",
    title: "Scanner de documentos no reconoce firmas",
    description: "El software de digitalización no reconoce el campo de firma en los formularios escaneados.",
    requester: "Antonia Vera",
    department: "Legal",
    category: "Software",
    priority: "media",
    status: "asignada",
    assignee: "Diego Fuentes",
    location: "Edificio Central — Piso 5",
    createdAt: "2026-08-13T13:40:00",
    updatedAt: "2026-08-13T14:00:00",
    slaDueAt: "2026-08-14T13:40:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Antonia Vera", author: "Antonia Vera", createdAt: "2026-08-13T13:40:00" },
    ],
  },
  {
    id: "INC-0110",
    title: "Portal de proveedores caído",
    description: "El portal de proveedores devuelve error 503 y los proveedores no pueden subir facturas.",
    requester: "Manuel Ortiz",
    department: "Finanzas",
    category: "Sistemas",
    priority: "critica",
    status: "asignada",
    assignee: "Adriano Lecaros",
    location: "Data Center",
    createdAt: "2026-08-14T06:50:00",
    updatedAt: "2026-08-14T07:10:00",
    slaDueAt: "2026-08-14T10:50:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Manuel Ortiz", author: "Manuel Ortiz", createdAt: "2026-08-14T06:50:00" },
      { id: "t2", type: "asignada", description: "Asignada a Adriano Lecaros", author: "Adriano Lecaros", createdAt: "2026-08-14T07:10:00" },
    ],
  },
  {
    id: "INC-0109",
    title: "Micrófono no funciona en Teams",
    description: "El micrófono no es detectado en Microsoft Teams tras última actualización de Windows.",
    requester: "Renata Gallardo",
    department: "Ventas",
    category: "Software",
    priority: "baja",
    status: "resuelta",
    assignee: "Matías Herrera",
    location: "Remoto",
    createdAt: "2026-08-12T09:20:00",
    updatedAt: "2026-08-12T10:15:00",
    slaDueAt: "2026-08-15T09:20:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Renata Gallardo", author: "Renata Gallardo", createdAt: "2026-08-12T09:20:00" },
      { id: "t2", type: "resuelta", description: "Se actualizaron los drivers de audio", author: "Matías Herrera", createdAt: "2026-08-12T10:15:00" },
    ],
  },
  {
    id: "INC-0108",
    title: "Cámara de seguridad del lobby sin señal",
    description: "La cámara de seguridad del lobby principal no transmite señal al sistema de monitoreo.",
    requester: "Héctor Peña",
    department: "Operaciones",
    category: "Red",
    priority: "media",
    status: "nueva",
    assignee: null,
    location: "Edificio Central — Lobby",
    createdAt: "2026-08-14T08:55:00",
    updatedAt: "2026-08-14T08:55:00",
    slaDueAt: "2026-08-15T08:55:00",
    slaBreached: false,
    attachments: [],
    comments: [],
    timeline: [
      { id: "t1", type: "creada", description: "Incidencia creada por Héctor Peña", author: "Héctor Peña", createdAt: "2026-08-14T08:55:00" },
    ],
  },
]

export const USERS: User[] = [
  { id: "U-001", name: "Adriano Lecaros", email: "adriano.lecaros@sigia.io", role: "administrador", department: "TI", status: "activo", lastActive: "Hace 2 min", assignedCount: 3 },
  { id: "U-002", name: "Camila Rojas", email: "camila.rojas@sigia.io", role: "tecnico", department: "TI", status: "activo", lastActive: "Hace 8 min", assignedCount: 4 },
  { id: "U-003", name: "Diego Fuentes", email: "diego.fuentes@sigia.io", role: "tecnico", department: "TI", status: "activo", lastActive: "Hace 15 min", assignedCount: 5 },
  { id: "U-004", name: "Valentina Soto", email: "valentina.soto@sigia.io", role: "tecnico", department: "TI", status: "activo", lastActive: "Hace 1 h", assignedCount: 3 },
  { id: "U-005", name: "Matías Herrera", email: "matias.herrera@sigia.io", role: "tecnico", department: "TI", status: "activo", lastActive: "Hace 25 min", assignedCount: 4 },
  { id: "U-006", name: "Lucía Ramírez", email: "lucia.ramirez@sigia.io", role: "supervisor", department: "TI", status: "activo", lastActive: "Hace 40 min", assignedCount: 0 },
  { id: "U-007", name: "María González", email: "maria.gonzalez@sigia.io", role: "usuario", department: "Operaciones", status: "activo", lastActive: "Hace 3 h", assignedCount: 0 },
  { id: "U-008", name: "Jorge Núñez", email: "jorge.nunez@sigia.io", role: "usuario", department: "Finanzas", status: "activo", lastActive: "Ayer", assignedCount: 0 },
  { id: "U-009", name: "Paula Vega", email: "paula.vega@sigia.io", role: "usuario", department: "Ventas", status: "inactivo", lastActive: "Hace 5 días", assignedCount: 0 },
  { id: "U-010", name: "Sofía Miranda", email: "sofia.miranda@sigia.io", role: "supervisor", department: "Ventas", status: "activo", lastActive: "Hace 1 h", assignedCount: 0 },
]

export const KB_ARTICLES: KbArticle[] = [
  { id: "KB-001", title: "Cómo restablecer tu contraseña de dominio", category: "Accesos", excerpt: "Guía paso a paso para restablecer tu contraseña de red corporativa desde el autoservicio.", views: 1284, updatedAt: "2026-08-01", helpful: 96 },
  { id: "KB-002", title: "Solución al error 'Credenciales inválidas' en SSO", category: "Accesos", excerpt: "Pasos para diagnosticar y resolver problemas de inicio de sesión único (SSO).", views: 842, updatedAt: "2026-08-10", helpful: 91 },
  { id: "KB-003", title: "Reiniciar el firmware de impresoras HP", category: "Impresoras", excerpt: "Procedimiento para resolver errores comunes como 49.4C02 en multifuncionales HP.", views: 523, updatedAt: "2026-07-22", helpful: 88 },
  { id: "KB-004", title: "Configurar la VPN corporativa en Windows y macOS", category: "Red", excerpt: "Instrucciones para instalar y estabilizar la conexión VPN de la empresa.", views: 1976, updatedAt: "2026-08-05", helpful: 94 },
  { id: "KB-005", title: "Reemplazo de módulos de RAM defectuosos", category: "Hardware", excerpt: "Cómo identificar y reemplazar memoria RAM ante pantallas azules recurrentes.", views: 312, updatedAt: "2026-06-30", helpful: 82 },
  { id: "KB-006", title: "Renovar certificados TLS de webhooks", category: "Integraciones", excerpt: "Guía para renovar certificados TLS y evitar fallos en integraciones externas.", views: 265, updatedAt: "2026-08-12", helpful: 90 },
  { id: "KB-007", title: "Instalar y activar licencias de Office 365", category: "Software", excerpt: "Proceso de asignación de licencias y activación de Microsoft Office 365.", views: 1120, updatedAt: "2026-07-18", helpful: 93 },
  { id: "KB-008", title: "Optimizar el rendimiento del servidor de correo", category: "Sistemas", excerpt: "Buenas prácticas para reducir la latencia en la entrega de correos internos.", views: 448, updatedAt: "2026-08-08", helpful: 85 },
]

// ---- Aggregations for charts ----

export const CREATED_VS_RESOLVED = [
  { month: "Feb", creadas: 18, resueltas: 15 },
  { month: "Mar", creadas: 22, resueltas: 20 },
  { month: "Abr", creadas: 19, resueltas: 21 },
  { month: "May", creadas: 25, resueltas: 23 },
  { month: "Jun", creadas: 28, resueltas: 26 },
  { month: "Jul", creadas: 24, resueltas: 25 },
  { month: "Ago", creadas: 27, resueltas: 22 },
]

export const SLA_MONTHLY = [
  { month: "Feb", cumplimiento: 88 },
  { month: "Mar", cumplimiento: 90 },
  { month: "Abr", cumplimiento: 87 },
  { month: "May", cumplimiento: 92 },
  { month: "Jun", cumplimiento: 94 },
  { month: "Jul", cumplimiento: 93 },
  { month: "Ago", cumplimiento: 91 },
]

export const RECURRING_PARETO = [
  { problema: "Fallo de acceso / SSO", cantidad: 34 },
  { problema: "VPN inestable", cantidad: 26 },
  { problema: "Impresoras", cantidad: 18 },
  { problema: "Licencias software", cantidad: 12 },
  { problema: "Integraciones API", cantidad: 9 },
  { problema: "Hardware periféricos", cantidad: 6 },
  { problema: "Otros", cantidad: 4 },
]

export const SLA_BY_PRIORITY = [
  { priority: "critica" as const, objetivo: "4 h", promedio: "3 h 12 m", cumplimiento: 86 },
  { priority: "alta" as const, objetivo: "8 h", promedio: "6 h 40 m", cumplimiento: 90 },
  { priority: "media" as const, objetivo: "24 h", promedio: "18 h 20 m", cumplimiento: 94 },
  { priority: "baja" as const, objetivo: "72 h", promedio: "40 h 05 m", cumplimiento: 97 },
]

export const TECHNICIANS = tech
