"use client"
import * as React from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import { useSigia } from "@/lib/store"
import { CATEGORIES, DEPARTMENTS, SYSTEM_PRODUCTS, PRIORITIES, STATUSES, ORIGINS, RESPONSIBLES, suggestedResponsible, type Priority, type Status } from "@/lib/types"
import { PageHeader } from "@/components/page-header"
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select"

export default function NuevaIncidenciaPage(){
 const router=useRouter(); const {addIncident}=useSigia();
 const [saving,setSaving]=React.useState(false)
 const [f,setF]=React.useState({module:"Agendamiento",title:"",origin:"Operación",date:new Date().toISOString().slice(0,10),reason:"",strategy:"",department:"GTI",priority:"media" as Priority,followUp:"",status:"nueva" as Status,systemProduct:"",relatedArea:"",requester:"",location:"",responsibleName:"Nelson Romero",externalDependency:false,externalProvider:""})
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!f.title.trim()){toast.error("Ingresa la incidencia");return}setSaving(true);try{const item=await addIncident({title:f.title,description:f.title,requester:f.requester,department:f.department,category:f.module,priority:f.priority,location:f.location,origin:f.origin,reason:f.reason,strategy:f.strategy,followUp:f.followUp,status:f.status,occurredAt:new Date(f.date+"T12:00:00").toISOString(),systemProduct:f.systemProduct||null,relatedAreas:f.relatedArea?[f.relatedArea]:[],responsibleName:f.responsibleName||null,externalDependency:f.externalDependency,externalProvider:f.externalProvider||null});toast.success(`${item.id} creada correctamente`);router.push(`/incidencias/${item.id}`)}catch(e:any){toast.error(e.message||"No se pudo crear") }finally{setSaving(false)}}
 return <div className="flex flex-col gap-6"><PageHeader title="Nueva incidencia" description="Formulario basado en el registro real de incidencias de MaipoSalud."/>
 <form onSubmit={submit}><Card><CardHeader><CardTitle>Registro de incidencia</CardTitle></CardHeader><CardContent className="grid gap-5">
  <div className="grid gap-4 md:grid-cols-2"><Field label="Módulo"><Select value={f.module} onValueChange={v=>setF({...f,module:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{CATEGORIES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Origen"><Select value={f.origin} onValueChange={v=>setF({...f,origin:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{ORIGINS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field></div>
  <Field label="Incidencia *"><Textarea className="min-h-24" value={f.title} onChange={e=>setF({...f,title:e.target.value})} placeholder="Describe el problema reportado"/></Field>
  <div className="grid gap-4 md:grid-cols-2"><Field label="Fecha"><Input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field><Field label="Criticidad"><Select value={f.priority} onValueChange={v=>setF({...f,priority:v as Priority})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{PRIORITIES.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></Field></div>
  <Field label="Motivo"><Textarea value={f.reason} onChange={e=>setF({...f,reason:e.target.value})} placeholder="Causa o motivo identificado"/></Field>
  <Field label="Estrategia"><Textarea value={f.strategy} onChange={e=>setF({...f,strategy:e.target.value})} placeholder="Acción, solución o estrategia propuesta"/></Field>
  <div className="grid gap-4 md:grid-cols-3"><Field label="Departamento principal"><Select value={f.department} onValueChange={v=>setF({...f,department:v,responsibleName:suggestedResponsible(f.systemProduct,v)||f.responsibleName})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{DEPARTMENTS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Área relacionada"><Select value={f.relatedArea||"ninguna"} onValueChange={v=>setF({...f,relatedArea:v==="ninguna"?"":v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ninguna">Ninguna</SelectItem>{DEPARTMENTS.filter(x=>x!==f.department).map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Sistema / Producto"><Select value={f.systemProduct||"ninguno"} onValueChange={v=>{const sp=v==="ninguno"?"":v;const ext=sp==="Fonasa"||sp==="IMED";setF({...f,systemProduct:sp,responsibleName:suggestedResponsible(sp,f.department)||"",externalDependency:ext,externalProvider:ext?sp:""})}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ninguno">No aplica</SelectItem>{SYSTEM_PRODUCTS.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field></div>
  <div className="grid gap-4 md:grid-cols-3"><Field label="Responsable"><Select value={f.responsibleName||"sin_asignar"} onValueChange={v=>setF({...f,responsibleName:v==="sin_asignar"?"":v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="sin_asignar">Sin asignar</SelectItem>{RESPONSIBLES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></Field><Field label="Dependencia externa"><Select value={f.externalDependency?"si":"no"} onValueChange={v=>setF({...f,externalDependency:v==="si",externalProvider:v==="si"?f.externalProvider:""})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="no">No</SelectItem><SelectItem value="si">Sí</SelectItem></SelectContent></Select></Field>{f.externalDependency?<Field label="Proveedor externo"><Select value={f.externalProvider||"Fonasa"} onValueChange={v=>setF({...f,externalProvider:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Fonasa">Fonasa</SelectItem><SelectItem value="IMED">IMED</SelectItem><SelectItem value="Otro">Otro</SelectItem></SelectContent></Select></Field>:<div/>}</div>
  <Field label="Update / Seguimiento"><Textarea value={f.followUp} onChange={e=>setF({...f,followUp:e.target.value})} placeholder="Última actualización o seguimiento"/></Field>
  <div className="grid gap-4 md:grid-cols-3"><Field label="Estado"><Select value={f.status} onValueChange={v=>setF({...f,status:v as Status})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{STATUSES.map(x=><SelectItem key={x.value} value={x.value}>{x.label}</SelectItem>)}</SelectContent></Select></Field><Field label="Solicitante (opcional)"><Input value={f.requester} onChange={e=>setF({...f,requester:e.target.value})}/></Field><Field label="Sucursal / ubicación (opcional)"><Input value={f.location} onChange={e=>setF({...f,location:e.target.value})}/></Field></div>
  <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>router.back()}>Cancelar</Button><Button type="submit" disabled={saving}>{saving?"Guardando...":"Crear incidencia"}</Button></div>
 </CardContent></Card></form></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-2"><Label>{label}</Label>{children}</div>}
